export const CHISME_ADDED_REQUESTED = 'CHISME_ADDED_REQUESTED';
export const CHISME_ADDED_SUCCESS = 'CHISME_ADDED_SUCCESS';
export const CHISME_DELETED_REQUESTED = 'CHISME_DELETED_REQUESTED'
export const CHISME_DELETED_SUCCESS = 'CHISME_DELETED_SUCCESS'
export const CHISME_UPDATED = 'CHISME_UPDATED'
export const ERROR_RAISED = 'ERROR_RAISED'
export const CHISMES_FETCH_REQUESTED = 'CHISMES_FETCH_REQUESTED'
export const CHISMES_FETCH_SUCCESS = 'CHISMES_FETCH_SUCCESS'
