export const CHISME_ADDED = 'CHISME_ADDED';
export const CHISME_DELETED = 'CHISME_DELETED'
export const CHISME_UPDATED = 'CHISME_UPDATED'
export const ERROR_RAISED = 'ERROR_RAISED'
export const CHISMES_FETCH_REQUESTED = 'CHISMES_FETCH_REQUESTED'
export const CHISMES_FETCH_SUCCESS = 'CHISMES_FETCH_SUCCESS'
